replicaCount: 1

image:
  tag: 532c823f70fa49585ef6bd4e1ac435b4398331b9

ingress:
  enabled: true
  host: spring-dev.local

config:
  LOG_LEVEL: "DEBUG"
  DB_HOST: "dev-db.local"
  DB_NAME: "mydb_dev"

secrets:
  DB_PASSWORD: "dev-password-123"
