replicaCount: 1

image:
  tag: ac76b567e0b450d10479622c4625a1878c2963cb

ingress:
  enabled: true
  host: nest-dev.local

config:
  SPRING_API_URL: "http://spring-api"
  LOG_LEVEL: "debug"

secrets:
  API_TOKEN: "dev-token-123"
